# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(980, 560)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 190, 560))
        self.widget.setStyleSheet("background-color: rgb(147, 183, 231);")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 561))
        self.layoutWidget.setObjectName("layoutWidget")
        self.meanLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.meanLayout.setContentsMargins(0, 0, 0, 0)
        self.meanLayout.setSpacing(0)
        self.meanLayout.setObjectName("meanLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.meanLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.bt_mean_min = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_mean_min.setObjectName("bt_mean_min")
        self.horizontalLayout_3.addWidget(self.bt_mean_min)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)
        self.horizontalLayout_3.setStretch(2, 30)
        self.meanLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.meanLayout.addItem(spacerItem3)
        self.lb_mean_icon = QtWidgets.QLabel(self.layoutWidget)
        self.lb_mean_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_mean_icon.setObjectName("lb_mean_icon")
        self.meanLayout.addWidget(self.lb_mean_icon)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.meanLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_mean_reps = QtWidgets.QLabel(self.layoutWidget)
        self.lb_mean_reps.setObjectName("lb_mean_reps")
        self.horizontalLayout_4.addWidget(self.lb_mean_reps)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.bt_mean_add_rep = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_mean_add_rep.setStyleSheet("background-image: url(:/b_add_store.png);\n"
"background-position:center;\n"
"background-repeat:no-repeat;")
        self.bt_mean_add_rep.setIconSize(QtCore.QSize(20, 20))
        self.bt_mean_add_rep.setObjectName("bt_mean_add_rep")
        self.horizontalLayout_4.addWidget(self.bt_mean_add_rep)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 5)
        self.horizontalLayout_4.setStretch(2, 1)
        self.meanLayout.addLayout(self.horizontalLayout_4)
        self.sa_mean_reps = QtWidgets.QScrollArea(self.layoutWidget)
        self.sa_mean_reps.setWidgetResizable(True)
        self.sa_mean_reps.setObjectName("sa_mean_reps")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 187, 240))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.lv_mean_reps = QtWidgets.QListView(self.scrollAreaWidgetContents_3)
        self.lv_mean_reps.setGeometry(QtCore.QRect(10, 10, 171, 201))
        self.lv_mean_reps.setObjectName("lv_mean_reps")
        self.sa_mean_reps.setWidget(self.scrollAreaWidgetContents_3)
        self.meanLayout.addWidget(self.sa_mean_reps)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.meanLayout.addItem(spacerItem6)
        self.lb_mean_mark_manager = QtWidgets.QLabel(self.layoutWidget)
        self.lb_mean_mark_manager.setObjectName("lb_mean_mark_manager")
        self.meanLayout.addWidget(self.lb_mean_mark_manager)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.meanLayout.addItem(spacerItem7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bt_mean_seting = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_mean_seting.setObjectName("bt_mean_seting")
        self.horizontalLayout_5.addWidget(self.bt_mean_seting)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.bt_mean_exit = QtWidgets.QPushButton(self.layoutWidget)
        self.bt_mean_exit.setStyleSheet("background-image: url(:/b_exit.png);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"background-position:center;\n"
"background-repeat:no-repeat;")
        self.bt_mean_exit.setAutoRepeat(False)
        self.bt_mean_exit.setObjectName("bt_mean_exit")
        self.horizontalLayout_5.addWidget(self.bt_mean_exit)
        self.meanLayout.addLayout(self.horizontalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.meanLayout.addItem(spacerItem9)
        self.meanLayout.setStretch(0, 1)
        self.meanLayout.setStretch(1, 4)
        self.meanLayout.setStretch(2, 2)
        self.meanLayout.setStretch(3, 8)
        self.meanLayout.setStretch(4, 2)
        self.meanLayout.setStretch(5, 4)
        self.meanLayout.setStretch(6, 40)
        self.meanLayout.setStretch(7, 2)
        self.meanLayout.setStretch(8, 4)
        self.meanLayout.setStretch(9, 20)
        self.meanLayout.setStretch(10, 4)
        self.meanLayout.setStretch(11, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(190, 0, 790, 560))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("background-image: url(:/background.jpg);\n"
"background-repeat:no-repeat;\n"
"background-position:center;\n"
"background-size:790px,560px")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(579, 0, 211, 560))
        self.widget_3.setStyleSheet("background-color: rgba(229, 229, 229, 100);")
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 0, 201, 561))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.detailLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.detailLayout.setContentsMargins(0, 0, 0, 0)
        self.detailLayout.setSpacing(0)
        self.detailLayout.setObjectName("detailLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.detailLayout.addItem(spacerItem10)
        self.lb_detail_filename = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_detail_filename.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_detail_filename.setObjectName("lb_detail_filename")
        self.detailLayout.addWidget(self.lb_detail_filename)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.detailLayout.addItem(spacerItem11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_detail_describe = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_detail_describe.setObjectName("lb_detail_describe")
        self.horizontalLayout.addWidget(self.lb_detail_describe)
        self.bt_detail_describe_save = QtWidgets.QPushButton(self.layoutWidget_3)
        self.bt_detail_describe_save.setObjectName("bt_detail_describe_save")
        self.horizontalLayout.addWidget(self.bt_detail_describe_save)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.horizontalLayout.setStretch(0, 20)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.detailLayout.addLayout(self.horizontalLayout)
        self.sa_detail_describe = QtWidgets.QScrollArea(self.layoutWidget_3)
        self.sa_detail_describe.setWidgetResizable(True)
        self.sa_detail_describe.setObjectName("sa_detail_describe")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 197, 106))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tf_detail_describr = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.tf_detail_describr.setGeometry(QtCore.QRect(10, 10, 171, 81))
        self.tf_detail_describr.setObjectName("tf_detail_describr")
        self.sa_detail_describe.setWidget(self.scrollAreaWidgetContents)
        self.detailLayout.addWidget(self.sa_detail_describe)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.detailLayout.addItem(spacerItem13)
        self.lb_detail_mark = QtWidgets.QLabel(self.layoutWidget_3)
        self.lb_detail_mark.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_detail_mark.setObjectName("lb_detail_mark")
        self.detailLayout.addWidget(self.lb_detail_mark)
        self.sa_detail_marks = QtWidgets.QScrollArea(self.layoutWidget_3)
        self.sa_detail_marks.setWidgetResizable(True)
        self.sa_detail_marks.setObjectName("sa_detail_marks")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 197, 287))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gb1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gb1.setGeometry(QtCore.QRect(10, 10, 171, 101))
        self.gb1.setObjectName("gb1")
        self.sa_detail_marks.setWidget(self.scrollAreaWidgetContents_2)
        self.detailLayout.addWidget(self.sa_detail_marks)
        self.detailLayout.setStretch(0, 1)
        self.detailLayout.setStretch(1, 2)
        self.detailLayout.setStretch(2, 1)
        self.detailLayout.setStretch(3, 2)
        self.detailLayout.setStretch(4, 6)
        self.detailLayout.setStretch(5, 1)
        self.detailLayout.setStretch(6, 2)
        self.detailLayout.setStretch(7, 16)
        self.layoutWidget_2 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 581, 561))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.mainLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.bt_main_show_card = QtWidgets.QPushButton(self.layoutWidget_2)
        self.bt_main_show_card.setObjectName("bt_main_show_card")
        self.horizontalLayout_6.addWidget(self.bt_main_show_card)
        self.bt_main_show_list = QtWidgets.QPushButton(self.layoutWidget_2)
        self.bt_main_show_list.setStyleSheet("background-image: url(:/b_liststyle2.png);\n"
"background-position:center;\n"
"background-repeat:no-repeat;")
        self.bt_main_show_list.setIconSize(QtCore.QSize(20, 20))
        self.bt_main_show_list.setObjectName("bt_main_show_list")
        self.horizontalLayout_6.addWidget(self.bt_main_show_list)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.horizontalLayout_6.setStretch(0, 20)
        self.horizontalLayout_6.setStretch(1, 4)
        self.horizontalLayout_6.setStretch(2, 4)
        self.horizontalLayout_6.setStretch(3, 10)
        self.mainLayout.addLayout(self.horizontalLayout_6)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem17)
        self.lb_main_path = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_main_path.setObjectName("lb_main_path")
        self.mainLayout.addWidget(self.lb_main_path)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem18)
        self.sa_main_fileList = QtWidgets.QScrollArea(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sa_main_fileList.sizePolicy().hasHeightForWidth())
        self.sa_main_fileList.setSizePolicy(sizePolicy)
        self.sa_main_fileList.setStyleSheet("background-color: rgba(218, 218, 218, 100);")
        self.sa_main_fileList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sa_main_fileList.setWidgetResizable(True)
        self.sa_main_fileList.setObjectName("sa_main_fileList")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 577, 456))
        self.scrollAreaWidgetContents_4.setStyleSheet("background-color: rgba(202, 202, 202, 100);")
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.lv_main_fileList = QtWidgets.QListView(self.scrollAreaWidgetContents_4)
        self.lv_main_fileList.setGeometry(QtCore.QRect(10, 10, 551, 391))
        self.lv_main_fileList.setObjectName("lv_main_fileList")
        self.sa_main_fileList.setWidget(self.scrollAreaWidgetContents_4)
        self.mainLayout.addWidget(self.sa_main_fileList)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem19)
        self.lb_main_status = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_main_status.setObjectName("lb_main_status")
        self.mainLayout.addWidget(self.lb_main_status)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem20)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 2)
        self.mainLayout.setStretch(2, 1)
        self.mainLayout.setStretch(3, 2)
        self.mainLayout.setStretch(4, 1)
        self.mainLayout.setStretch(5, 50)
        self.mainLayout.setStretch(6, 1)
        self.mainLayout.setStretch(7, 1)
        self.mainLayout.setStretch(8, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.bt_mean_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_mean_min.setText(_translate("MainWindow", "返回"))
        self.lb_mean_icon.setText(_translate("MainWindow", "头像"))
        self.lb_mean_reps.setText(_translate("MainWindow", "  仓库  "))
        self.bt_mean_add_rep.setText(_translate("MainWindow", "        "))
        self.lb_mean_mark_manager.setText(_translate("MainWindow", "  标签管理"))
        self.bt_mean_seting.setText(_translate("MainWindow", "设置"))
        self.bt_mean_exit.setText(_translate("MainWindow", "        "))
        self.lb_detail_filename.setText(_translate("MainWindow", "文件名"))
        self.lb_detail_describe.setText(_translate("MainWindow", "    描述    "))
        self.bt_detail_describe_save.setText(_translate("MainWindow", "Save"))
        self.lb_detail_mark.setText(_translate("MainWindow", "    标签"))
        self.gb1.setTitle(_translate("MainWindow", "GroupBox"))
        self.bt_main_show_card.setText(_translate("MainWindow", "PushButton"))
        self.bt_main_show_list.setText(_translate("MainWindow", "        "))
        self.lb_main_path.setText(_translate("MainWindow", "  当前路径"))
        self.lb_main_status.setText(_translate("MainWindow", "  状态信息"))
import pic_rc
