# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesktop_h.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 609)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    border-image: url(:/background.jpg);\n"
"}\n"
"QTextEdit#textEdit{\n"
"    background-color: rgba(53, 92, 125, 150);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_1.setObjectName("widget_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_1)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.widget_1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lb_cpu = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_cpu.setFont(font)
        self.lb_cpu.setObjectName("lb_cpu")
        self.verticalLayout_6.addWidget(self.lb_cpu)
        self.lb_ram = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_ram.setFont(font)
        self.lb_ram.setObjectName("lb_ram")
        self.verticalLayout_6.addWidget(self.lb_ram)
        self.lb_rom = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_rom.setFont(font)
        self.lb_rom.setObjectName("lb_rom")
        self.verticalLayout_6.addWidget(self.lb_rom)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lb_time = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_time.setFont(font)
        self.lb_time.setObjectName("lb_time")
        self.verticalLayout_7.addWidget(self.lb_time)
        self.lb_date = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_date.setFont(font)
        self.lb_date.setObjectName("lb_date")
        self.verticalLayout_7.addWidget(self.lb_date)
        self.listView = QtWidgets.QListView(self.widget_5)
        self.listView.setObjectName("listView")
        self.verticalLayout_7.addWidget(self.listView)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_cpu.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">TextLabel</p></body></html>"))
        self.lb_ram.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">TextLabel</p></body></html>"))
        self.lb_rom.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">TextLabel</p></body></html>"))
        self.lb_time.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.lb_date.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
import pic_rc
