# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fconfirm(object):
    def setupUi(self, Fconfirm):
        Fconfirm.setObjectName("Fconfirm")
        Fconfirm.resize(600, 800)
        Fconfirm.setMinimumSize(QtCore.QSize(600, 800))
        Fconfirm.setMaximumSize(QtCore.QSize(600, 800))
        self.verticalLayout = QtWidgets.QVBoxLayout(Fconfirm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Fconfirm)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hl_1_1 = QtWidgets.QHBoxLayout()
        self.hl_1_1.setObjectName("hl_1_1")
        self.lb_number = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_number.setFont(font)
        self.lb_number.setObjectName("lb_number")
        self.hl_1_1.addWidget(self.lb_number)
        self.le_number = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_number.setFont(font)
        self.le_number.setObjectName("le_number")
        self.hl_1_1.addWidget(self.le_number)
        self.lb_name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_name.setFont(font)
        self.lb_name.setObjectName("lb_name")
        self.hl_1_1.addWidget(self.lb_name)
        self.le_name = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_name.setFont(font)
        self.le_name.setObjectName("le_name")
        self.hl_1_1.addWidget(self.le_name)
        self.hl_1_1.setStretch(0, 1)
        self.hl_1_1.setStretch(1, 2)
        self.hl_1_1.setStretch(2, 1)
        self.hl_1_1.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.hl_1_1)
        self.hl_1_2 = QtWidgets.QHBoxLayout()
        self.hl_1_2.setObjectName("hl_1_2")
        self.lb_people = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_people.setFont(font)
        self.lb_people.setObjectName("lb_people")
        self.hl_1_2.addWidget(self.lb_people)
        self.le_people = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_people.setFont(font)
        self.le_people.setObjectName("le_people")
        self.hl_1_2.addWidget(self.le_people)
        self.lb_tel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_tel.setFont(font)
        self.lb_tel.setObjectName("lb_tel")
        self.hl_1_2.addWidget(self.lb_tel)
        self.le_tel = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_tel.setFont(font)
        self.le_tel.setObjectName("le_tel")
        self.hl_1_2.addWidget(self.le_tel)
        self.hl_1_2.setStretch(0, 1)
        self.hl_1_2.setStretch(1, 2)
        self.hl_1_2.setStretch(2, 1)
        self.hl_1_2.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.hl_1_2)
        self.line_1 = QtWidgets.QFrame(self.widget)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout_2.addWidget(self.line_1)
        self.hl_2_1 = QtWidgets.QHBoxLayout()
        self.hl_2_1.setObjectName("hl_2_1")
        self.lb_color = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_color.setFont(font)
        self.lb_color.setObjectName("lb_color")
        self.hl_2_1.addWidget(self.lb_color)
        self.cb_color = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_color.setFont(font)
        self.cb_color.setObjectName("cb_color")
        self.hl_2_1.addWidget(self.cb_color)
        self.lb_logo = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_logo.setFont(font)
        self.lb_logo.setObjectName("lb_logo")
        self.hl_2_1.addWidget(self.lb_logo)
        self.le_logo = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_logo.setFont(font)
        self.le_logo.setObjectName("le_logo")
        self.hl_2_1.addWidget(self.le_logo)
        self.hl_2_1.setStretch(0, 1)
        self.hl_2_1.setStretch(1, 2)
        self.hl_2_1.setStretch(2, 1)
        self.hl_2_1.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.hl_2_1)
        self.hl_2_2 = QtWidgets.QHBoxLayout()
        self.hl_2_2.setObjectName("hl_2_2")
        self.lb_type = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_type.setFont(font)
        self.lb_type.setObjectName("lb_type")
        self.hl_2_2.addWidget(self.lb_type)
        self.cb_type = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_type.setFont(font)
        self.cb_type.setObjectName("cb_type")
        self.hl_2_2.addWidget(self.cb_type)
        self.lb_count = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_count.setFont(font)
        self.lb_count.setObjectName("lb_count")
        self.hl_2_2.addWidget(self.lb_count)
        self.le_count = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_count.setFont(font)
        self.le_count.setObjectName("le_count")
        self.hl_2_2.addWidget(self.le_count)
        self.hl_2_2.setStretch(0, 1)
        self.hl_2_2.setStretch(1, 2)
        self.hl_2_2.setStretch(2, 1)
        self.hl_2_2.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.hl_2_2)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.hl_3_1 = QtWidgets.QHBoxLayout()
        self.hl_3_1.setObjectName("hl_3_1")
        self.lb_board = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_board.setFont(font)
        self.lb_board.setObjectName("lb_board")
        self.hl_3_1.addWidget(self.lb_board)
        self.cb_board = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_board.setFont(font)
        self.cb_board.setObjectName("cb_board")
        self.hl_3_1.addWidget(self.cb_board)
        self.lb_screen = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_screen.setFont(font)
        self.lb_screen.setObjectName("lb_screen")
        self.hl_3_1.addWidget(self.lb_screen)
        self.cb_screen = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_screen.setFont(font)
        self.cb_screen.setObjectName("cb_screen")
        self.hl_3_1.addWidget(self.cb_screen)
        self.hl_3_1.setStretch(0, 1)
        self.hl_3_1.setStretch(1, 2)
        self.hl_3_1.setStretch(2, 1)
        self.hl_3_1.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.hl_3_1)
        self.hl_3_3 = QtWidgets.QHBoxLayout()
        self.hl_3_3.setObjectName("hl_3_3")
        self.lb_camera = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_camera.setFont(font)
        self.lb_camera.setObjectName("lb_camera")
        self.hl_3_3.addWidget(self.lb_camera)
        self.cb_camera = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_camera.setFont(font)
        self.cb_camera.setObjectName("cb_camera")
        self.hl_3_3.addWidget(self.cb_camera)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.rb_has_m3 = QtWidgets.QRadioButton(self.groupBox)
        self.rb_has_m3.setObjectName("rb_has_m3")
        self.horizontalLayout_12.addWidget(self.rb_has_m3)
        self.rb_no_m3 = QtWidgets.QRadioButton(self.groupBox)
        self.rb_no_m3.setChecked(True)
        self.rb_no_m3.setObjectName("rb_no_m3")
        self.horizontalLayout_12.addWidget(self.rb_no_m3)
        self.hl_3_3.addWidget(self.groupBox)
        self.hl_3_3.setStretch(0, 1)
        self.hl_3_3.setStretch(1, 2)
        self.hl_3_3.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.hl_3_3)
        self.hl_3_2 = QtWidgets.QHBoxLayout()
        self.hl_3_2.setObjectName("hl_3_2")
        self.lb_id = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_id.setFont(font)
        self.lb_id.setObjectName("lb_id")
        self.hl_3_2.addWidget(self.lb_id)
        self.cb_id = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_id.setFont(font)
        self.cb_id.setObjectName("cb_id")
        self.hl_3_2.addWidget(self.cb_id)
        self.lb_finger = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_finger.setFont(font)
        self.lb_finger.setObjectName("lb_finger")
        self.hl_3_2.addWidget(self.lb_finger)
        self.cb_finger = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_finger.setFont(font)
        self.cb_finger.setObjectName("cb_finger")
        self.hl_3_2.addWidget(self.cb_finger)
        self.hl_3_2.setStretch(0, 1)
        self.hl_3_2.setStretch(1, 2)
        self.hl_3_2.setStretch(2, 1)
        self.hl_3_2.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.hl_3_2)
        self.hl_3_4 = QtWidgets.QHBoxLayout()
        self.hl_3_4.setObjectName("hl_3_4")
        self.lb_wire = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_wire.setFont(font)
        self.lb_wire.setObjectName("lb_wire")
        self.hl_3_4.addWidget(self.lb_wire)
        self.cb_wire = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_wire.setFont(font)
        self.cb_wire.setObjectName("cb_wire")
        self.hl_3_4.addWidget(self.cb_wire)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_yes_step = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_yes_step.setChecked(True)
        self.rb_yes_step.setObjectName("rb_yes_step")
        self.horizontalLayout.addWidget(self.rb_yes_step)
        self.rb_no_step = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_no_step.setObjectName("rb_no_step")
        self.horizontalLayout.addWidget(self.rb_no_step)
        self.hl_3_4.addWidget(self.groupBox_2)
        self.hl_3_4.setStretch(0, 1)
        self.hl_3_4.setStretch(1, 2)
        self.hl_3_4.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.hl_3_4)
        self.lb_other = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_other.setFont(font)
        self.lb_other.setObjectName("lb_other")
        self.verticalLayout_2.addWidget(self.lb_other)
        self.hl_4_6 = QtWidgets.QHBoxLayout()
        self.hl_4_6.setObjectName("hl_4_6")
        self.chb_gm = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chb_gm.setFont(font)
        self.chb_gm.setObjectName("chb_gm")
        self.hl_4_6.addWidget(self.chb_gm)
        self.chb_m1 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chb_m1.setFont(font)
        self.chb_m1.setObjectName("chb_m1")
        self.hl_4_6.addWidget(self.chb_m1)
        self.chb_battery = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chb_battery.setFont(font)
        self.chb_battery.setObjectName("chb_battery")
        self.hl_4_6.addWidget(self.chb_battery)
        self.chb_4g = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chb_4g.setFont(font)
        self.chb_4g.setObjectName("chb_4g")
        self.hl_4_6.addWidget(self.chb_4g)
        self.chb_stand = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chb_stand.setFont(font)
        self.chb_stand.setObjectName("chb_stand")
        self.hl_4_6.addWidget(self.chb_stand)
        self.verticalLayout_2.addLayout(self.hl_4_6)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.hl_4_1 = QtWidgets.QHBoxLayout()
        self.hl_4_1.setObjectName("hl_4_1")
        self.lb_software = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_software.setFont(font)
        self.lb_software.setObjectName("lb_software")
        self.hl_4_1.addWidget(self.lb_software)
        self.le_software = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_software.setFont(font)
        self.le_software.setObjectName("le_software")
        self.hl_4_1.addWidget(self.le_software)
        self.hl_4_1.setStretch(0, 1)
        self.hl_4_1.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.hl_4_1)
        self.hl_4_2 = QtWidgets.QHBoxLayout()
        self.hl_4_2.setObjectName("hl_4_2")
        self.lb_hardware = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_hardware.setFont(font)
        self.lb_hardware.setObjectName("lb_hardware")
        self.hl_4_2.addWidget(self.lb_hardware)
        self.le_hardware = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_hardware.setFont(font)
        self.le_hardware.setObjectName("le_hardware")
        self.hl_4_2.addWidget(self.le_hardware)
        self.hl_4_2.setStretch(0, 1)
        self.hl_4_2.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.hl_4_2)
        self.hl_4_3 = QtWidgets.QHBoxLayout()
        self.hl_4_3.setObjectName("hl_4_3")
        self.lb_m3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_m3.setFont(font)
        self.lb_m3.setObjectName("lb_m3")
        self.hl_4_3.addWidget(self.lb_m3)
        self.le_m3 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_m3.setFont(font)
        self.le_m3.setObjectName("le_m3")
        self.hl_4_3.addWidget(self.le_m3)
        self.hl_4_3.setStretch(0, 1)
        self.hl_4_3.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.hl_4_3)
        self.hl_4_4 = QtWidgets.QHBoxLayout()
        self.hl_4_4.setObjectName("hl_4_4")
        self.lb_mark = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_mark.setFont(font)
        self.lb_mark.setObjectName("lb_mark")
        self.hl_4_4.addWidget(self.lb_mark)
        self.te_mark = QtWidgets.QTextEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.te_mark.setFont(font)
        self.te_mark.setObjectName("te_mark")
        self.hl_4_4.addWidget(self.te_mark)
        self.hl_4_4.setStretch(0, 1)
        self.hl_4_4.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.hl_4_4)
        self.hl_4_5 = QtWidgets.QHBoxLayout()
        self.hl_4_5.setObjectName("hl_4_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_4_5.addItem(spacerItem)
        self.bt_submit = QtWidgets.QPushButton(self.widget)
        self.bt_submit.setObjectName("bt_submit")
        self.hl_4_5.addWidget(self.bt_submit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_4_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.hl_4_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_2.setStretch(6, 1)
        self.verticalLayout_2.setStretch(8, 1)
        self.verticalLayout_2.setStretch(9, 1)
        self.verticalLayout_2.setStretch(10, 1)
        self.verticalLayout_2.setStretch(11, 1)
        self.verticalLayout_2.setStretch(12, 1)
        self.verticalLayout_2.setStretch(13, 1)
        self.verticalLayout_2.setStretch(14, 1)
        self.verticalLayout_2.setStretch(15, 1)
        self.verticalLayout_2.setStretch(16, 5)
        self.verticalLayout_2.setStretch(17, 1)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Fconfirm)
        self.bt_submit.clicked.connect(Fconfirm.slotBtSubmit)
        QtCore.QMetaObject.connectSlotsByName(Fconfirm)

    def retranslateUi(self, Fconfirm):
        _translate = QtCore.QCoreApplication.translate
        Fconfirm.setWindowTitle(_translate("Fconfirm", "Form"))
        self.lb_number.setText(_translate("Fconfirm", "订单号"))
        self.lb_name.setText(_translate("Fconfirm", "客户名称"))
        self.lb_people.setText(_translate("Fconfirm", "商务"))
        self.lb_tel.setText(_translate("Fconfirm", "电话"))
        self.lb_color.setText(_translate("Fconfirm", "颜色"))
        self.lb_logo.setText(_translate("Fconfirm", "丝印"))
        self.le_logo.setText(_translate("Fconfirm", "无"))
        self.lb_type.setText(_translate("Fconfirm", "型号"))
        self.lb_count.setText(_translate("Fconfirm", "数量"))
        self.lb_board.setText(_translate("Fconfirm", "主板"))
        self.lb_screen.setText(_translate("Fconfirm", "显示屏"))
        self.lb_camera.setText(_translate("Fconfirm", "摄像头"))
        self.groupBox.setTitle(_translate("Fconfirm", "键盘"))
        self.rb_has_m3.setText(_translate("Fconfirm", "有"))
        self.rb_no_m3.setText(_translate("Fconfirm", "无"))
        self.lb_id.setText(_translate("Fconfirm", "二代证"))
        self.lb_finger.setText(_translate("Fconfirm", "指纹仪"))
        self.lb_wire.setText(_translate("Fconfirm", "电缆线"))
        self.groupBox_2.setTitle(_translate("Fconfirm", "开机"))
        self.rb_yes_step.setText(_translate("Fconfirm", "非同步"))
        self.rb_no_step.setText(_translate("Fconfirm", "同步"))
        self.lb_other.setText(_translate("Fconfirm", "其他可选项"))
        self.chb_gm.setText(_translate("Fconfirm", "国密"))
        self.chb_m1.setText(_translate("Fconfirm", "禾嘉读卡器"))
        self.chb_battery.setText(_translate("Fconfirm", "电池"))
        self.chb_4g.setText(_translate("Fconfirm", "4G模块"))
        self.chb_stand.setText(_translate("Fconfirm", "支架"))
        self.lb_software.setText(_translate("Fconfirm", "应用程序"))
        self.lb_hardware.setText(_translate("Fconfirm", "固件版本"))
        self.lb_m3.setText(_translate("Fconfirm", "M3版本"))
        self.lb_mark.setText(_translate("Fconfirm", "备注"))
        self.bt_submit.setText(_translate("Fconfirm", "确定"))

    def setChoiceData(self, info):
        # 定义选择框的数据
        # [color, type, board, screen, camera, id, finger, wire]
        self.addComboxData(self.cb_color, info[0])
        self.cb_type.addItem('')
        self.addComboxData(self.cb_type, info[1])
        self.cb_board.addItem('')
        self.addComboxData(self.cb_board, info[2])
        self.cb_screen.addItem('')
        self.addComboxData(self.cb_screen, info[3])
        self.addComboxData(self.cb_camera, info[4])
        self.addComboxData(self.cb_id, info[5])
        self.addComboxData(self.cb_finger, info[6])
        self.cb_wire.addItem('')
        self.addComboxData(self.cb_wire, info[7])

    def addComboxData(self, combox, data):
        for i in data:
            combox.addItem(i)

    def getInput(self):
        # 定义返回数组：订单号，客户名称，商务，电话，颜色，丝印，型号，数量
        # 主板，显示屏，摄像头，键盘，二代证，指纹仪，电缆线， 同步开机
        # 国密，禾嘉读卡器，电池，4G，支架
        # 应用程序版本，固件版本，m3版本，备注
        info = [self.le_number.displayText(), self.le_name.displayText(), self.le_people.displayText(),
                self.le_tel.displayText(), self.cb_color.currentText(), self.le_logo.displayText(),
                self.cb_type.currentText(), self.le_count.displayText(), self.cb_board.currentText(),
                self.cb_screen.currentText(), self.cb_camera.currentText(),
                '有按键板' if (self.rb_has_m3.isChecked()) else '无按键板',
                self.cb_id.currentText(), self.cb_finger.currentText(),
                self.cb_wire.currentText(),
                '非同步' if (self.rb_no_step.isChecked()) else '同步',
                '国密' if (self.chb_gm.isChecked()) else '无国密',
                '禾嘉读卡器' if (self.chb_m1.isChecked()) else '',
                '电池' if (self.chb_battery.isChecked()) else '',
                '4G模块' if (self.chb_4g.isChecked()) else '',
                '有支架' if (self.chb_stand.isChecked()) else '无支架',
                self.le_software.displayText(), self.le_hardware.displayText(), self.le_m3.displayText(),
                self.te_mark.toPlainText()]
        return info
